export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGRIDIENTS = 'SET_INGRIDIENTS';
export const FETCH_INGRIDIENTS_FAILED = 'FETCH_INGRIDIENTS_FAILED';